nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - /Users/zongbao/dev:/opt

php:
    build: ./php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "redis"
    volumes:
      - /Users/zongbao/dev:/opt

mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - /Users/zongbao/dev/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

redis:
    build: ./redis
    ports:
      - "6379:6379"
paddle:
    image: "paddlepaddle/book"
    ports:
      - "8888:8888"
    links:
      - "php"
    volumes:
      - /Users/zongbao/dev:/opt
#docker run -d -p 8888:8888 paddlepaddle/book